### ISSUE TITLE
Audio starts playing automatically (Linux)

### ISSUE THREAD

**Issue by ryanheise** [sagudev/just_audio_vlc#1]
To reproduce, edit the official just_audio example with this dependency:

```yaml
  just_audio_vlc:
    git:
      url: https://github.com/sagudev/just_audio_vlc.git
```

And run with:

```bash
flutter run -d linux
```

Although interestingly, the playlist example runs properly without automatically playing:

```bash
flutter run -d linux -t lib/example_playlist.dart
```

Other than this, the plugin seems to be working very nicely.
